# Generated by Django 4.0.6 on 2023-03-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_caretaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_warden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('college_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('room_num', models.CharField(max_length=10)),
                ('hostel', models.CharField(choices=[('', 'Choose'), ('Hostel A', 'Hostel A'), ('Hostel B', 'Hostel B'), ('Hostel C', 'Hostel C'), ('Hostel D', 'Hostel D'), ('Hostel E', 'Hostel E'), ('Hostel F', 'Hostel F'), ('Hostel G', 'Hostel G'), ('Hostel H', 'Hostel H'), ('Hostel I', 'Hostel I'), ('Hostel J', 'Hostel J'), ('Hostel K', 'Hostel K'), ('Hostel L', 'Hostel L'), ('Hostel M', 'Hostel M'), ('Hostel N', 'Hostel N'), ('Hostel O', 'Hostel O')], max_length=10)),
                ('mobile_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
