# Generated by Django 4.0.6 on 2023-03-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room_num',
        ),
    ]
