# Generated by Django 4.0.6 on 2023-03-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_warden_caretaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_name', models.CharField(choices=[('', 'Choose'), ('Hostel A', 'Hostel A'), ('Hostel B', 'Hostel B'), ('Hostel C', 'Hostel C'), ('Hostel D', 'Hostel D'), ('Hostel E', 'Hostel E'), ('Hostel F', 'Hostel F'), ('Hostel G', 'Hostel G'), ('Hostel H', 'Hostel H'), ('Hostel I', 'Hostel I'), ('Hostel J', 'Hostel J'), ('Hostel K', 'Hostel K'), ('Hostel L', 'Hostel L'), ('Hostel M', 'Hostel M'), ('Hostel N', 'Hostel N'), ('Hostel O', 'Hostel O')], max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, max_length=3)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.caretaker')),
                ('warden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.warden')),
            ],
        ),
    ]
