# Generated by Django 4.0.6 on 2023-03-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='capacity',
            field=models.IntegerField(blank=True),
        ),
    ]
