# Generated by Django 4.0.6 on 2023-03-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_hostel_caretaker_remove_hostel_warden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=5)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hostel')),
            ],
        ),
    ]
