# Generated by Django 4.0.6 on 2023-03-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_num',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
